# cluster_config.yml - cluster configuration
__default__:
    time: 03:30:00 # time limit for each job
    nodes: 4
    ntasks-per-node: 1 #Request n cores be allocated per node.
    memory: 50G

assign_porec_fragments:
    time: 00:25:00
    nodes: 1
    ntasks-per-node: 1
    memory: 20G

assign_pairs:
    time: 00:59:00
    nodes: 1
    ntasks-per-node: 1
    memory: 120G

assign_fragments:
    time: 00:05:00
    nodes: 1
    ntasks-per-node: 1
    memory: 10G

align_bwa:
    time: 04:00:00
    nodes: 8
    ntasks-per-node: 1
    memory: 55G

call_brdu:
    time: 03:30:00
    nodes: 20
    ntasks-per-node: 1
    memory: 15G

create_qc_pore_c:
    time: 03:30:00
    nodes: 1
    ntasks-per-node: 1
    memory: 90G

create_qc_sister_pore_c:
    time: 00:30:00
    nodes: 1
    ntasks-per-node: 1
    memory: 20G

create_alignment_table:
    time: 00:05:00
    nodes: 1
    ntasks-per-node: 1
    memory: 1G

import_basecalls:
    time: 02:00:00
    nodes: 1
    ntasks-per-node: 1
    memory: 10G

haplotag:
    time: 00:05:00
    nodes: 1
    ntasks-per-node: 1
    memory: 2G 

remove_index_from_readname:
    time: 00:05:00
    nodes: 1
    ntasks-per-node: 1
    memory: 2G

to_contacts:
    time: 00:10:00
    nodes: 1
    ntasks-per-node: 1
    memory: 5G  

to_label_coolers:
    time: 00:05:00
    nodes: 1
    ntasks-per-node: 1
    memory: 5G

transfer_weights:
    time: 00:05:00
    nodes: 1
    ntasks-per-node: 1
    memory: 1G

split_pairs:
    time: 02:30:00
    nodes: 1
    ntasks-per-node: 1
    memory: 90G

zoomify_and_balance_label_coolers:
    time: 00:30:00
    nodes: 4
    ntasks-per-node: 1
    memory: 10G

summarise_contacts:
    time: 06:30:00
    nodes: 1
    ntasks-per-node: 1
    memory: 25G

merge_triplets:
    time: 00:59:00
    nodes: 1
    ntasks-per-node: 1
    memory: 40G
