# cluster_config.yml - cluster configuration
__default__:
    time: 03:30:00 # time limit for each job
    nodes: 4
    ntasks-per-node: 1 #Request n cores be allocated per node.
    memory: 50G

align_bwa:
    time: 04:00:00
    nodes: 8
    ntasks-per-node: 1
    memory: 55G

call_brdu:
    time: 03:30:00
    nodes: 20
    ntasks-per-node: 1
    memory: 15G

assign_pairs:
    time: 00:30:00
    nodes: 1
    ntasks-per-node: 1
    memory: 120G

split_pairs:
    time: 02:30:00
    nodes: 1
    ntasks-per-node: 1
    memory: 90G

zoomify_and_balance_label_coolers:
    time: 00:30:00
    nodes: 10
    ntasks-per-node: 1
    memory: 20G

summarise_contacts:
    time: 06:30:00
    nodes: 1
    ntasks-per-node: 1
    memory: 25G

merge_triplets:
    time: 00:30:00
    nodes: 1
    ntasks-per-node: 1
    memory: 40G
